### ISSUE TITLE
Double Pulverizer recipes?

### ISSUE THREAD

**Issue by Akitori** [TehSeph/NetherFoundation#2]
![2018-04-27_14 16 21](https://user-images.githubusercontent.com/24502131/39381028-462574b6-4a26-11e8-9b7e-33f2e870eb91.png)

Yeah, not sure why but there's one recipe adding sulfur, one adding nothing.

Thermal Expansion 5.4.1.24
Nether Foundation 1.0

**Comment by KingLemming** [comment]
This is happening because PulverizerManager is being directly referenced and TE otherwise has auto-logic to pick things up. That's bad. :(

IMC should be used for this and not direct manager referencing.

**Comment by TehSeph** [comment]
Huh. I didn't encounter this in testing. Using IMC is something I've been looking into and guess should be priority now. I'll admit, I'm not sure exactly how to create the NBTMessage objects. :|

@KingLemming While I have you here, any suggestions for creating the Petrotheum/Pyrotheum recipes without oredict (undesirable results) or my messy manual recipes that currently exist? Or are those okay and just the TE recipes need fixing?

**Comment by KingLemming** [comment]
Unfortunately the specialization recipes are a bit of a hard code - the machines do either +1 or +50%, whichever is more. They just know to do it with certain categories of items - Ores and Clusters in the Pulverizer, and only Ores for the Smelter.

Good news is, I've actually changed things up so that what you're doing here is actually alright. Basically you were sending your recipes before I'd initialized the managers, since I hadn't expected anyone to be calling those methods straight out. I've since changed when "init" happens and when it's acceptable to do so.

So if you want, leave as is. It's alright. If you would prefer to do NBT instead though, feel free to either use:
https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/api/util/ThermalExpansionHelper.java

or copy the relevant methods and strings out of it completely and make your own helper file. Either is totally fine. :)

BTW, nice work on the mod.

**Comment by TehSeph** [comment]
Since CoFHCore is already a required dependency I'll go ahead and switch over to using that helper class. I'd rather do things properly than just do them because they happen to work. I originally went this route because it is how CraftTweaker appears to be handling TE recipes and I couldn't find any examples of using IMC. I'm not new to Java or Forge mods per se, but I am still relatively inexperienced, so a lot of my code is crafted by looking at other mods. Thanks for the praises. 😊

**Comment by KingLemming** [comment]
CraftTweaker should not be doing that. >:(

**Comment by TehSeph** [comment]
https://github.com/jaredlll08/ModTweaker/tree/1.12/src/main/java/com/blamejared/compat/thermalexpansion (*ModTweaker, my bad)

Also I should have clarified above, I meant the TF dust recipes not the augmented machine recipes.

@Akitori Anyway, I'll leave this issue open until this properly fixed on my end, but it sounds like updating to the latest CoFHCore and Thermal Expansion should resolve the duplicate recipes.

**Comment by KingLemming** [comment]
BTW, while I have your attention, possibly get rid of the max version for CoFHCore? I don't know exactly when the next update will be, but it will be 4.5.0 and your current mod apparently won't work with that.

There are some big under the hood changes, but nothing that should affect you.

In fact, you could just do a required-after: thermalfoundation and that's enough, since it has the other deps already.

**Comment by TehSeph** [comment]
Ah, sure thing. I was only using the VERSION_GROUP constants out of laziness so I wouldn't need to update those lines each time you updated, just recompile. I hadn't even thought of just using `require-after`. I guess my concern there is not having a new enough version installed, but I can just specify a minimum. Will do. :)

**Comment by TehSeph** [comment]
~~With the changes you've made to Thermal Foundation's deps, will I also need a line for CoFH World?~~
I suppose I don't need to since TF doesn't and both sets of worldgen config code are identical. Though an ore mod without oregen seems nonsensical. lol I might anyway.

**Comment by TehSeph** [comment]
If you'd like, we can open a new issue I'll leave open for continued discussion on any future changes to the CoFH mods I'll need pay attention to. I understand that is probably asking more of you than expected outside of your own projects, so it is your choice. I believe the original issue has been solved though, unless I'm mistaken.

**Comment by KingLemming** [comment]
Looks good. The reason I suggest removing CoFHWorld as a hard dep is because it's not even a hard dep for Thermal Foundation anymore. Technically, modpack makers are able to use other oregen mods (such as geolosys if they prefer.

On Curse, however, it's still considered to be a hard dep for stupid proofing. I'm just providing an advanced option for pack makers.
